export const UPDATE_CARS = "UPDATE_CARS";
export const ADD_WISH_LIST = "ADD_WISH_LIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const CLEAR_WISHLIST = "CLEAR_WISHLIST";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";